### ISSUE TITLE
Highlighter not working correctly in touch screen mode

### ISSUE THREAD

**Issue by binbin0219** [ThatOpen/engine_components#476]
### Describe the bug 📝

In touch screen mode, the objects cannot be selected by touching the screen.  The bug can be found in the documentation https://docs.thatopen.com/Tutorials/Components/Front/Highlighter

### System Info 💻

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 Intel(R) Core(TM) i9-14900HX
    Memory: 5.25 GB / 15.63 GB
  Binaries:
    Node: 21.7.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Fixed from `@thatopne/components@2.3.7`!

**Comment by binbin0219** [comment]
Thank you for your update but I tried just now with this version @thatopne/components@2.3.7, but the bug is still there

**Comment by binbin0219** [comment]
![image](https://github.com/user-attachments/assets/2284cdc8-468c-47a4-9f55-910e91b98703)
![image](https://github.com/user-attachments/assets/f49300ea-5d58-4c1a-a5ca-090dd00f1a9e)
It is the same. Is my Highlighter setup wrong?

**Comment by binbin0219** [comment]
Forget about that boss, it works now, thank you
